#@ load("@ytt:data", "data")
---
profile: iterate
ceip_policy_disclosed: true # Installation fails if this is set to 'false'
buildservice:
  kp_default_repository: #@ "{}/build-service/bundle".format(data.values.container_registry.hostname)
  kp_default_repository_username: #@ data.values.container_registry.username
  kp_default_repository_password: #@ data.values.container_registry.password
  tanzunet_username: #@ data.values.tanzunet.username
  tanzunet_password: #@ data.values.tanzunet.password
  enable_automatic_dependency_updates: false
  exclude_dependencies: true

supply_chain: basic

api-auto-registration:
  tap_gui_url: #@ "https://tap-gui.{}".format(data.values.ingress.tap-gui-domain)
  cluster_name: iterate-cluster

appsso:
  domain_name: #@ "apps.{}".format(data.values.ingress.domain)
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

ootb_supply_chain_basic:
  registry:
    server: #@ data.values.container_registry.hostname
    repository: "apps"
  gitops:
    ssh_secret: ""

contour:
  envoy:
    service:
      annotations:      
        external-dns.alpha.kubernetes.io/hostname: #@ "*.{}".format(data.values.ingress.domain)
      type: LoadBalancer

cnrs:
  domain_name: #@ "apps.{}".format(data.values.ingress.domain)
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
  default_tls_secret: #@ "{}/cnr-{}".format(data.values.ingress.contour_tls_namespace,data.values.ingress.contour_tls_secret)

grype:
  namespace: #@ data.values.developer_namespace
  targetImagePullSecret: registry-credentials

appliveview_connector:
  backend:
    sslDisabled: "true"
    host: #@ "appliveview.view.{}".format(data.values.ingress.domain)
