#@ load("@ytt:data", "data")
---
profile: build
ceip_policy_disclosed: true # Installation fails if this is set to 'false'
buildservice:
  kp_default_repository: #@ "{}/build-service/bundle".format(data.values.container_registry.hostname)
  kp_default_repository_username: #@ data.values.container_registry.username
  kp_default_repository_password: #@ data.values.container_registry.password
  tanzunet_username: #@ data.values.tanzunet.username
  tanzunet_password: #@ data.values.tanzunet.password
  enable_automatic_dependency_updates: false
  exclude_dependencies: true

supply_chain: testing_scanning

ootb_supply_chain_testing_scanning:
  registry:
    server: #@ data.values.container_registry.hostname
    repository: "apps"
  gitops:
    server_address: https://github.com/
    repository_owner: #@ data.values.gitops.repo_owner
    repository_name: #@ data.values.gitops.repo_name
    branch: main
    commit_strategy: pull_request
    ssh_secret: git-https
    pull_request:
      server_kind: github
      commit_branch: ""
      pull_request_title: "New Gitops pull request is ready for review"
      pull_request_body: "This pull request was generated by a supply chain"

ootb_supply_chain_basic:
  registry:
    server: #@ data.values.container_registry.hostname
    repository: "apps"
  gitops:
    server_address: https://github.com/
    repository_owner: #@ data.values.gitops.repo_owner
    repository_name: #@ data.values.gitops.repo_name
    branch: test
    commit_strategy: pull_request
    ssh_secret: git-https
    pull_request:
      server_kind: github
      commit_branch: ""
      pull_request_title: New Gitop pull request is ready for review
      pull_request_body: This pull request was generated by a supply chain

scanning:
 metadataStore: 
   url: ""

grype:
  namespace: #@ data.values.developer_namespace
  targetImagePullSecret: registry-credentials
  metadataStore:
    url: #@ "https://metadata-store.{}".format(data.values.ingress.domain)
    caSecret:
        name: store-ca-cert
        importFromNamespace: metadata-store-secrets
    authSecret:
        name: store-auth-token
        importFromNamespace: metadata-store-secrets

excluded_packages:
  - contour.tanzu.vmware.com
