apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tap-iterate
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-2xlarge
      storageClass: vc01cl01-t0compute
      tkr:  
        reference:
          name: v1.22.9---vmware.1-tkg.1.cc71bc8
    nodePools:
    - name: workers
      replicas: 1
      vmClass: best-effort-8xlarge
      storageClass: vc01cl01-t0compute
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 100Gi
      tkr:  
        reference:
          name: v1.22.9---vmware.1-tkg.1.cc71bc8
  settings:
    storage:
      classes: [vc01cl01-t0compute]
      defaultClass: vc01cl01-t0compute
